### ISSUE TITLE
No SLF4J providers were found.

### ISSUE THREAD

**Issue by brad-eric** [LarryDpk/Google-Bard#16]
I can build the library successfully, but when running my code AIClient client = new GoogleBardClient( "my_bard_key" ); i get this exception:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See https://www.slf4j.org/codes.html#noProviders for further details.
java.lang.NoClassDefFoundError: okhttp3/OkHttpClient$Builder
	at com.pkslow.ai.util.WebUtils.okHttpClientWithTimeout(WebUtils.java:14)
	at com.pkslow.ai.GoogleBardClient.<init>(GoogleBardClient.java:33)
	at com.pkslow.ai.GoogleBardClient.<init>(GoogleBardClient.java:28)
```

How can i fix this please?

**Comment by LarryDpk** [comment]
missing okhttp, try to reload or re-download the dependencies

**Comment by LarryDpk** [comment]
any luck?

**Comment by LarryDpk** [comment]
will close as no more reply
