### ISSUE TITLE
Abnormal operation

### ISSUE THREAD

**Issue by ashengovo** [LarryDpk/Google-Bard#2]
16:14:04.253 [main] INFO com.pkslow.ai.WebUtils -- Creating OkHttpClient with timeout PT5M
16:14:05.010 [main] INFO com.pkslow.ai.WebUtils -- OkHttpClient created
16:14:06.371 [main] INFO com.pkslow.ai.GoogleBardClient -- getSNlM0e Response code: 200
java.lang.NullPointerException: Parameter specified as non-null is null: method okhttp3.FormBody$Builder.add, parameter value
	at okhttp3.FormBody$Builder.add(FormBody.kt)
	at com.pkslow.ai.GoogleBardClient.requestBodyForAsk(GoogleBardClient.java:141)
	at com.pkslow.ai.GoogleBardClient.postRequestForAsk(GoogleBardClient.java:120)
	at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:95)
	at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:41)
	at com.pkslow.ai.GoogleBardExample.main(GoogleBardExample.java:15)

**Comment by LarryDpk** [comment]
It's a timeout issue, please make sure the network is accessable to US. And remember to set proxy before you start to chat:
```java
NetworkUtils.setUpProxy("localhost", "7890");
```

And also make sure you got the token and pass in the API call.

**Comment by LarryDpk** [comment]
As no response for a long time, will close.
