### ISSUE TITLE
Getting ConnectException: Failed to connect to localhost:7890

### ISSUE THREAD

**Issue by jtrbk** [LarryDpk/Google-Bard#21]
Hi,  I am trying to run this code (using v 0.3.5) and I am getting the exception shown below.  I am running this from the US.  Is this region supported?

`		String token = t1 + ";" + t2;
		
		NetworkUtils.setUpProxy("127.0.0.1", "7890");
		AIClient client = new GoogleBardClient(token, Duration.ofMinutes(10));
		Answer answer = client.ask("Tell me a joke");
		
		if (answer.getStatus() == AnswerStatus.OK) {
			System.out.println(answer.markdown());
		}
		else {
			System.out.println(answer.toString());
		}`

I get the following exception...
`
01:22:29.450 [main] INFO com.pkslow.ai.util.WebUtils -- Creating OkHttpClient with timeout PT10M
01:22:29.722 [main] INFO com.pkslow.ai.util.WebUtils -- OkHttpClient created
01:22:29.764 [main] ERROR com.pkslow.ai.GoogleBardClient -- Failed to get answer: 
java.lang.RuntimeException: java.net.ConnectException: Failed to connect to /127.0.0.1:7890
	at com.pkslow.ai.GoogleBardClient.callBardToGetSNlM0e(GoogleBardClient.java:73)
	at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:42)
	at AI.Bard.main(Bard.java:21)
Caused by: java.net.ConnectException: Failed to connect to /127.0.0.1:7890
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:261)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.pkslow.ai.GoogleBardClient.callBardToGetSNlM0e(GoogleBardClient.java:68)
	... 2 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
	... 19 common frames omitted
Answer(status=ERROR, chosenAnswer=null, images=null)
`

**Comment by LarryDpk** [comment]
oh. if you are in US, no need to set proxy, please remove this: `NetworkUtils.setUpProxy("127.0.0.1", "7890");`

**Comment by LarryDpk** [comment]
close this as no more response
