### ISSUE TITLE
Unexpected response code for CONNECT: 501

### ISSUE THREAD

**Issue by bela-dona** [LarryDpk/Google-Bard#5]
20:01:50.436 [main] INFO com.pkslow.ai.WebUtils -- Creating OkHttpClient with timeout PT10M
20:01:51.466 [main] INFO com.pkslow.ai.WebUtils -- OkHttpClient created
java.lang.RuntimeException: java.io.IOException: Unexpected response code for CONNECT: 501
	at com.pkslow.ai.GoogleBardClient.getSNlM0e(GoogleBardClient.java:186)
	at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:50)
	at org.example.GoogleBardExample.main(GoogleBardExample.java:15)
Caused by: java.io.IOException: Unexpected response code for CONNECT: 501
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:483)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.pkslow.ai.GoogleBardClient.getSNlM0e(GoogleBardClient.java:179)
	... 2 more
	Suppressed: java.io.IOException: Unexpected response code for CONNECT: 501
		... 20 more
java.lang.RuntimeException: java.io.IOException: Unexpected response code for CONNECT: 501
	at com.pkslow.ai.GoogleBardClient.getSNlM0e(GoogleBardClient.java:186)
	at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:50)
	at org.example.GoogleBardExample.main(GoogleBardExample.java:18)
Caused by: java.io.IOException: Unexpected response code for CONNECT: 501
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:483)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.pkslow.ai.GoogleBardClient.getSNlM0e(GoogleBardClient.java:179)
	... 2 more
	Suppressed: java.io.IOException: Unexpected response code for CONNECT: 501
		... 20 more
java.lang.RuntimeException: java.io.IOException: Unexpected response code for CONNECT: 501
	at com.pkslow.ai.GoogleBardClient.getSNlM0e(GoogleBardClient.java:186)
	at com.pkslow.ai.GoogleBardClient.ask(GoogleBardClient.java:50)
	at org.example.GoogleBardExample.main(GoogleBardExample.java:21)
Caused by: java.io.IOException: Unexpected response code for CONNECT: 501
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.kt:483)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:262)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
	at com.pkslow.ai.GoogleBardClient.getSNlM0e(GoogleBardClient.java:179)
	... 2 more
	Suppressed: java.io.IOException: Unexpected response code for CONNECT: 501
		... 20 more

**Comment by LarryDpk** [comment]
This is IO issues, maybe due to network. Did you get the token?

**Comment by LarryDpk** [comment]
will close as no more response
